# vim:fileencoding=utf-8:foldmethod=marker

# Usability
confirm_os_window_close 0
window_padding_width 0 4 4 4

## Fix issue with ssh & backspace
term xterm-256color

## Allow remote control nécessaire pour les sessions kitty
allow_remote_control yes
listen_on unix:/tmp/kitty-{kitty_pid}

# Editor
editor kitty

# Raccourcis pour mes sessions
map ctrl+a>d goto_session ~/.dotfiles/kitty/sessions/dotfiles.kitty-session
map ctrl+a>h goto_session ~/.dotfiles/kitty/sessions/home.kitty-session
map ctrl+a>b goto_session ~/.dotfiles/kitty/sessions/brain.kitty-session
map ctrl+a>n goto_session ~/.dotfiles/kitty/sessions/daily.kitty-session
map ctrl+a>j goto_session ~/.dotfiles/kitty/sessions/journal.kitty-session
map ctrl+a>r goto_session ~/.dotfiles/kitty/sessions/rofimark.kitty-session
map ctrl+a>i goto_session ~/.dotfiles/kitty/sessions/imgtools.kitty-session
map ctrl+a>c goto_session ~/.dotfiles/kitty/sessions/cours.kitty-session


# Lancement du script menu des sessions kitty
map ctrl+a>s launch --type=overlay bash -c "~/.dotfiles/kitty/scripts/ks.sh"

# Bonus : raccourci pour sélectionner graphiquement parmi tes sessions connues
# map ctrl+a>s goto_session

# Keymap
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+c copy_or_interrupt
map ctrl+alt+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+v paste_from_clipboard
map ctrl+enter launch --cwd=current
#map ctrl+q close_window
map ctrl+right next_window
map ctrl+left next_window

# Files exploration
map ctrl+e kitten choose-files .


# Tabs
tab_bar_min_tabs            1
tab_bar_align               left
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         round
# tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''
tab_title_template          "{tab.active_wd.rsplit('/', 1)[-1]}"
tab_bar_margin_height 0.0 2.0
# window_padding_width 0


# Permet de ne voir que les onglets de la session active
tab_bar_filter session:~ or session:^$

# Appearance
font_family FiraCode Nerd Font
italic_font VictorMonoNF-Italic
font_size 11
background_opacity 0.95

# Make kitty borderless
# "yes" disables round corners and hides the title bar
# "titlebar-only" leaves round corners but hides title bar
hide_window_decorations titlebar_only

# Tall layout: disposition des tabs (gauche verticale et droite horizontale)
enabled_layouts tall:bias=50;full_size=1;mirrored=false

# Fat layout
# enabled_layouts fat:bias=50;full_size=1;mirrored=false

## Animate cursor
cursor_trail 3
cursor_trail_decay 0.1 0.4

url_color #8be9fd

# Tab bar
active_tab_foreground   #282a36
active_tab_background   #ff79c6
inactive_tab_foreground #f8f8f2
inactive_tab_background #6272a4
tab_bar_background      #1e1e2f

## OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Scrollback qui ouvre nvim avec l'historique de la session kitty
# Super utile pour retrouver les résultats de mes recherches et les erreurs éventuelles
map ctrl+shift+h show_scrollback
scrollback_pager nvim -u NONE -R -M -c 'lua require("denis.kitty_scrollback")(INPUT_LINE_NUMBER, CURSOR_LINE, CURSOR_COLUMN)' -

# Color theme.
include theme.conf

