preload = /home/denis/Images/wallpaper/arcane1.jpg
preload = /home/denis/Images/wallpaper/saturne.jpg

wallpaper {
    monitor = eDP-1
    path = /home/denis/Images/wallpaper/arcane1.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/denis/Images/wallpaper/saturne.jpg
    fit_mode = cover
}
