preload = /home/denis/Images/wallpaper/lakshmi.png
preload = /home/denis/Images/wallpaper/195.jpg

wallpaper {
    monitor = eDP-1
    path = /home/denis/Images/wallpaper/lakshmi.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/denis/Images/wallpaper/195.jpg
    fit_mode = cover
}
