preload = /home/denis/Images/wallpaper/137.jpg
preload = /home/denis/Images/wallpaper/output/lune2.jpg

wallpaper {
    monitor = eDP-1
    path = /home/denis/Images/wallpaper/137.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/denis/Images/wallpaper/output/lune2.jpg
    fit_mode = cover
}
