preload = /home/denis/Images/wallpaper/161.jpg
preload = /home/denis/Images/wallpaper/aurora2.jpg

wallpaper {
    monitor = eDP-1
    path = /home/denis/Images/wallpaper/161.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/denis/Images/wallpaper/aurora2.jpg
    fit_mode = cover
}
