-- data.lua — base émotionnelle Comitys
-- Source : cartes Comitys (émotions + besoins)
-- Associations émotions → besoins : proposition automatique — à affiner selon ton ressenti
-- Format : { id, main, synonyms, needs_ids, needs }

local M = {}

M.emotions = {
	{ id = 1, main = "abattu", synonyms = { "préoccupé", "soucieux" }, needs_ids = { 1, 22, 43, 57 }, needs = { "tendresse", "consolation", "repos", "écoute" }, wounds = { "abandon" } },
	{ id = 2, main = "affectueux", synonyms = { "aimant", "attendri" }, needs_ids = { 1, 11, 17, 29 }, needs = { "tendresse", "chaleur", "complicité", "donner" }, wounds = {} },
	{ id = 3, main = "amer", synonyms = { "désabusé", "sombre" }, needs_ids = { 34, 20, 58 }, needs = { "justice", "confrontation", "honnêteté" }, wounds = { "trahison", "injustice" } },
	{ id = 4, main = "anxieux", synonyms = { "angoissé", "crispé" }, needs_ids = { 47, 6, 43, 55 }, needs = { "sécurité", "ancrage", "repos", "stabilité" }, wounds = { "abandon", "rejet" } },
	{ id = 5, main = "assommé", synonyms = { "abasourdi", "choqué" }, needs_ids = { 22, 57, 47 }, needs = { "consolation", "écoute", "sécurité" }, wounds = { "rejet" } },
	{ id = 6, main = "blasé", synonyms = { "détaché", "indifférent" }, needs_ids = { 48, 5, 13 }, needs = { "sens", "enthousiasme", "renaître" }, wounds = { "rejet", "abandon" } },
	{ id = 7, main = "bloqué", synonyms = { "emmuré", "emprisonné" }, needs_ids = { 36, 14, 26 }, needs = { "liberté", "choisir", "respirer" }, wounds = { "rejet", "injustice" } },
	{
		id = 8,
		main = "brisé",
		synonyms = { "broyé", "pulvérisé" },
		needs_ids = { 22, 32, 13, 37 },
		needs = { "consolation", "reconstruction", "renaître", "réconciliation" },
		wounds = { "abandon", "trahison" },
	},
	{ id = 9, main = "calme", synonyms = { "serein", "zen" }, needs_ids = { 8, 49, 35 }, needs = { "harmonie", "sérénité", "lâcher-prise" }, wounds = {} },
	{ id = 10, main = "coincé", synonyms = { "comprimé", "enserré" }, needs_ids = { 36, 26, 14 }, needs = { "liberté", "respirer", "choisir" }, wounds = { "rejet", "injustice" } },
	{ id = 11, main = "compatissant", synonyms = { "empathique", "séduit" }, needs_ids = { 9, 22, 57 }, needs = { "bienveillance", "consolation", "écoute" }, wounds = {} },
	{ id = 12, main = "concentré", synonyms = { "impliqué", "tendu" }, needs_ids = { 48, 15, 10 }, needs = { "sens", "cohérence", "cadre" }, wounds = {} },
	{ id = 13, main = "curieux", synonyms = { "absorbé", "captivé" }, needs_ids = { 24, 42, 3 }, needs = { "explorer", "réfléchir", "espoir" }, wounds = {} },
	{ id = 14, main = "déchiré", synonyms = { "écartelé", "tiraillé" }, needs_ids = { 18, 15, 14 }, needs = { "comprendre", "cohérence", "choisir" }, wounds = { "trahison", "abandon" } },
	{ id = 15, main = "découragé", synonyms = { "désespéré", "résigné" }, needs_ids = { 3, 22, 40 }, needs = { "espoir", "consolation", "reconnaissance" }, wounds = { "rejet", "abandon" } },
	{ id = 16, main = "dégoûté", synonyms = { "écœuré", "nauséeux" }, needs_ids = { 39, 58, 34 }, needs = { "propreté", "honnêteté", "justice" }, wounds = { "humiliation" } },
	{ id = 17, main = "déséquilibré", synonyms = { "flottant", "instable" }, needs_ids = { 6, 55, 8 }, needs = { "ancrage", "stabilité", "harmonie" }, wounds = { "abandon" } },
	{ id = 18, main = "désolé", synonyms = { "affligé", "navré" }, needs_ids = { 22, 30, 37 }, needs = { "consolation", "faire", "réconciliation" }, wounds = { "trahison" } },
	{ id = 19, main = "détendu", synonyms = { "apaisé", "décontracté" }, needs_ids = { 35, 43, 49 }, needs = { "lâcher-prise", "repos", "sérénité" }, wounds = {} },
	{ id = 20, main = "différent", synonyms = { "étranger", "exilé" }, needs_ids = { 4, 17, 55 }, needs = { "intégration", "complicité", "stabilité" }, wounds = { "rejet" } },
	{ id = 21, main = "effrayé", synonyms = { "terrifié", "tourmenté" }, needs_ids = { 47, 9, 6 }, needs = { "sécurité", "bienveillance", "ancrage" }, wounds = { "abandon", "rejet" } },
	{ id = 22, main = "émerveillé", synonyms = { "admiratif", "enchanté" }, needs_ids = { 5, 54, 24 }, needs = { "enthousiasme", "spiritualité", "explorer" }, wounds = {} },
	{ id = 23, main = "enthousiaste", synonyms = { "propulsé", "transporté" }, needs_ids = { 5, 7, 25 }, needs = { "enthousiasme", "créer", "défi" }, wounds = {} },
	{ id = 24, main = "épouvanté", synonyms = { "affolé", "horrifié" }, needs_ids = { 47, 9, 50 }, needs = { "sécurité", "bienveillance", "soins" }, wounds = { "abandon", "rejet" } },
	{ id = 25, main = "épuisé", synonyms = { "éreinté", "usé" }, needs_ids = { 43, 50, 32 }, needs = { "repos", "soins", "reconstruction" }, wounds = { "abandon" } },
	{ id = 26, main = "excité", synonyms = { "énergique", "fébrile" }, needs_ids = { 5, 36, 38 }, needs = { "enthousiasme", "liberté", "jouer" }, wounds = {} },
	{ id = 27, main = "fier", synonyms = { "content", "satisfait" }, needs_ids = { 40, 56, 7 }, needs = { "reconnaissance", "victoire", "créer" }, wounds = {} },
	{ id = 28, main = "fort", synonyms = { "indestructible", "puissant" }, needs_ids = { 44, 56, 25 }, needs = { "résister", "victoire", "défi" }, wounds = {} },
	{ id = 29, main = "frustré", synonyms = { "contrarié", "irrité" }, needs_ids = { 14, 18, 36 }, needs = { "choisir", "comprendre", "liberté" }, wounds = { "injustice", "trahison" } },
	{ id = 30, main = "furieux", synonyms = { "exaspéré", "excédé" }, needs_ids = { 20, 34, 58 }, needs = { "confrontation", "justice", "honnêteté" }, wounds = { "trahison", "injustice" } },
	{ id = 31, main = "grognon", synonyms = { "maussade", "râleur" }, needs_ids = { 23, 35, 43 }, needs = { "défoulement", "lâcher-prise", "repos" }, wounds = { "injustice" } },
	{ id = 32, main = "handicapé", synonyms = { "chancelant", "invalide" }, needs_ids = { 50, 32, 6 }, needs = { "soins", "reconstruction", "ancrage" }, wounds = { "humiliation", "rejet" } },
	{ id = 33, main = "honteux", synonyms = { "coupable", "penaud" }, needs_ids = { 37, 22, 58 }, needs = { "réconciliation", "consolation", "honnêteté" }, wounds = { "humiliation" } },
	{ id = 34, main = "impuissant", synonyms = { "démuni", "désemparé" }, needs_ids = { 53, 9, 40 }, needs = { "aide", "bienveillance", "reconnaissance" }, wounds = { "rejet", "humiliation" } },
	{ id = 35, main = "indécis", synonyms = { "dérouté", "perplexe" }, needs_ids = { 18, 42, 14 }, needs = { "comprendre", "réfléchir", "choisir" }, wounds = {} },
	{ id = 36, main = "inquiet", synonyms = { "apeuré", "stressé" }, needs_ids = { 47, 9, 57 }, needs = { "sécurité", "bienveillance", "écoute" }, wounds = { "abandon", "rejet" } },
	{ id = 37, main = "inspiré", synonyms = { "exalté", "passionné" }, needs_ids = { 5, 7, 54 }, needs = { "enthousiasme", "créer", "spiritualité" }, wounds = {} },
	{ id = 38, main = "intimidé", synonyms = { "embarrassé", "gêné" }, needs_ids = { 45, 4, 57 }, needs = { "respect", "intégration", "écoute" }, wounds = { "humiliation", "rejet" } },
	{ id = 39, main = "jaloux", synonyms = { "agacé", "envieux" }, needs_ids = { 34, 40, 20 }, needs = { "justice", "reconnaissance", "confrontation" }, wounds = { "injustice", "trahison" } },
	{ id = 40, main = "joueur", synonyms = { "amusé", "malicieux" }, needs_ids = { 38, 33, 5 }, needs = { "jouer", "rire", "enthousiasme" }, wounds = {} },
	{ id = 41, main = "joyeux", synonyms = { "épanoui", "gai" }, needs_ids = { 33, 12, 38 }, needs = { "rire", "célébrer", "jouer" }, wounds = {} },
	{ id = 42, main = "libre", synonyms = { "léger", "vivant" }, needs_ids = { 36, 26, 35 }, needs = { "liberté", "respirer", "lâcher-prise" }, wounds = {} },
	{ id = 43, main = "méfiant", synonyms = { "défiant", "soupçonneux" }, needs_ids = { 47, 15, 58 }, needs = { "sécurité", "cohérence", "honnêteté" }, wounds = { "trahison" } },
	{ id = 44, main = "motivé", synonyms = { "déterminé", "résolu" }, needs_ids = { 25, 56, 48 }, needs = { "défi", "victoire", "sens" }, wounds = {} },
	{ id = 45, main = "mou", synonyms = { "apathique", "démotivé" }, needs_ids = { 43, 5, 48 }, needs = { "repos", "enthousiasme", "sens" }, wounds = { "rejet", "abandon" } },
	{ id = 46, main = "nostalgique", synonyms = { "endeuillé", "mélancolique" }, needs_ids = { 30, 13, 54 }, needs = { "faire", "renaître", "spiritualité" }, wounds = { "abandon" } },
	{ id = 47, main = "noyé", synonyms = { "dépassé", "submergé" }, needs_ids = { 50, 53, 57 }, needs = { "soins", "aide", "écoute" }, wounds = { "abandon", "rejet" } },
	{ id = 48, main = "perdu", synonyms = { "déconcerté", "désorienté" }, needs_ids = { 18, 42, 6 }, needs = { "comprendre", "réfléchir", "ancrage" }, wounds = { "abandon" } },
	{ id = 49, main = "protégé", synonyms = { "préservé", "rassuré" }, needs_ids = { 47, 9, 55 }, needs = { "sécurité", "bienveillance", "stabilité" }, wounds = {} },
	{ id = 50, main = "reconnaissant", synonyms = { "comblé", "réjoui" }, needs_ids = { 29, 40, 12 }, needs = { "donner", "reconnaissance", "célébrer" }, wounds = {} },
	{ id = 51, main = "renouvelé", synonyms = { "changé", "transformé" }, needs_ids = { 13, 32, 3 }, needs = { "renaître", "reconstruction", "espoir" }, wounds = {} },
	{ id = 52, main = "révolté", synonyms = { "indigné", "scandalisé" }, needs_ids = { 20, 34, 31 }, needs = { "confrontation", "justice", "lutter" }, wounds = { "injustice", "trahison" } },
	{
		id = 53,
		main = "rongé",
		synonyms = { "empoisonné", "intoxiqué" },
		needs_ids = { 37, 32, 39 },
		needs = { "réconciliation", "reconstruction", "propreté" },
		wounds = { "trahison", "humiliation" },
	},
	{ id = 54, main = "sensible", synonyms = { "ému", "touché" }, needs_ids = { 57, 11, 1 }, needs = { "écoute", "chaleur", "tendresse" }, wounds = {} },
	{ id = 55, main = "seul", synonyms = { "coupé", "isolé" }, needs_ids = { 4, 16, 11 }, needs = { "intégration", "échanges", "chaleur" }, wounds = { "rejet", "abandon" } },
	{ id = 56, main = "soulagé", synonyms = { "délivré", "libéré" }, needs_ids = { 35, 37, 8 }, needs = { "lâcher-prise", "réconciliation", "harmonie" }, wounds = {} },
	{ id = 57, main = "surpris", synonyms = { "étonné", "stupéfait" }, needs_ids = { 57, 3, 42 }, needs = { "écoute", "espoir", "réfléchir" }, wounds = {} },
	{ id = 58, main = "triste", synonyms = { "chagriné", "peiné" }, needs_ids = { 22, 1, 30 }, needs = { "consolation", "tendresse", "faire" }, wounds = { "abandon" } },
	{ id = 59, main = "vide", synonyms = { "creux", "effacé" }, needs_ids = { 48, 13, 6 }, needs = { "sens", "renaître", "ancrage" }, wounds = { "rejet", "abandon" } },
}

M.besoins = {
	{ id = 1, main = "tendresse", full = "besoin de tendresse ", synonyms = { "affection", "douceur" } },
	{ id = 2, main = "oser", full = "besoin d'oser ", synonyms = { "entreprendre", "franchir" } },
	{ id = 3, main = "espoir", full = "besoin d'espoir ", synonyms = { "ouvertures", "perspectives" } },
	{ id = 4, main = "intégration", full = "besoin d'intégration ", synonyms = { "appartenance", "inclusion" } },
	{ id = 5, main = "enthousiasme", full = "besoin d'enthousiasme ", synonyms = { "émerveillement", "euphorie" } },
	{ id = 6, main = "ancrage", full = "besoin d'ancrage ", synonyms = { "enracinement", "fondations" } },
	{ id = 7, main = "créer", full = "besoin de créer ", synonyms = { "fabriquer", "réaliser" } },
	{ id = 8, main = "harmonie", full = "besoin d'harmonie ", synonyms = { "confort", "fluidité" } },
	{ id = 9, main = "bienveillance", full = "besoin de bienveillance ", synonyms = { "compassion", "protection" } },
	{ id = 10, main = "cadre", full = "besoin de cadre ", synonyms = { "adhésion", "engagement" } },
	{ id = 11, main = "chaleur", full = "besoin de chaleur ", synonyms = { "contact", "proximité" } },
	{ id = 12, main = "célébrer", full = "besoin de célébrer ", synonyms = { "fête", "réjouissances" } },
	{ id = 13, main = "renaître", full = "besoin de renaître ", synonyms = { "éclosion", "renouvellement" } },
	{ id = 14, main = "choisir", full = "besoin de choisir ", synonyms = { "décider", "résoudre" } },
	{ id = 15, main = "cohérence", full = "besoin de cohérence ", synonyms = { "cohésion", "unité" } },
	{ id = 16, main = "échanges", full = "besoin d'échanges ", synonyms = { "partage", "réseau" } },
	{ id = 17, main = "complicité", full = "besoin de complicité ", synonyms = { "communion", "connivence" } },
	{ id = 18, main = "comprendre", full = "besoin de comprendre ", synonyms = { "clarifier", "dénouer" } },
	{ id = 19, main = "piloter", full = "besoin de piloter ", synonyms = { "conduire", "encadrer" } },
	{ id = 20, main = "confrontation", full = "besoin de confrontation ", synonyms = { "affronter", "contredire" } },
	{ id = 21, main = "accompagnement", full = "besoin d'accompagnement ", synonyms = { "apprentissage", "initiation" } },
	{ id = 22, main = "consolation", full = "besoin de consolation ", synonyms = { "empathie", "réconfort" } },
	{ id = 23, main = "défoulement", full = "besoin de défoulement ", synonyms = { "éliminer", "évacuer" } },
	{ id = 24, main = "explorer", full = "besoin d'explorer ", synonyms = { "découvrir", "voyager" } },
	{ id = 25, main = "défi", full = "besoin de défi ", synonyms = { "compétition", "dépassement" } },
	{ id = 26, main = "respirer", full = "besoin de respirer ", synonyms = { "espace", "lumière" } },
	{ id = 27, main = "parler", full = "besoin de parler ", synonyms = { "raconter", "révéler" } },
	{ id = 28, main = "discerner", full = "besoin de discerner ", synonyms = { "évaluer", "juger" } },
	{ id = 29, main = "donner", full = "besoin de donner ", synonyms = { "offrir", "transmettre" } },
	{ id = 30, main = "faire", full = "besoin de faire son deuil ", synonyms = { "pleurer", "renoncer" } },
	{ id = 31, main = "lutter", full = "besoin de lutter ", synonyms = { "attaquer", "combattre" } },
	{ id = 32, main = "reconstruction", full = "besoin de reconstruction ", synonyms = { "cicatrisation", "régénération" } },
	{ id = 33, main = "rire", full = "besoin de rire ", synonyms = { "gaieté", "joie" } },
	{ id = 34, main = "justice", full = "besoin de justice ", synonyms = { "équité", "loyauté" } },
	{ id = 35, main = "lâcher-prise", full = "besoin de lâcher-prise ", synonyms = { "décontraction", "détachement" } },
	{ id = 36, main = "liberté", full = "besoin de liberté ", synonyms = { "autonomie", "élan" } },
	{ id = 37, main = "réconciliation", full = "besoin de réconciliation ", synonyms = { "paix", "pardon" } },
	{ id = 38, main = "jouer", full = "besoin de jouer ", synonyms = { "divertissement", "plaisir" } },
	{ id = 39, main = "propreté", full = "besoin de propreté ", synonyms = { "hygiène", "purification" } },
	{ id = 40, main = "reconnaissance", full = "besoin de reconnaissance ", synonyms = { "considération", "encouragement" } },
	{ id = 41, main = "ranger", full = "besoin de ranger ", synonyms = { "contrôler", "organiser" } },
	{ id = 42, main = "réfléchir", full = "besoin de réfléchir ", synonyms = { "échafauder", "imaginer" } },
	{ id = 43, main = "repos", full = "besoin de repos ", synonyms = { "détente", "récupération" } },
	{ id = 44, main = "résister", full = "besoin de résister ", synonyms = { "faire face", "tenir bon" } },
	{ id = 45, main = "respect", full = "besoin de respect ", synonyms = { "courtoisie", "politesse" } },
	{ id = 46, main = "rêver", full = "besoin de rêver ", synonyms = { "évasion", "folie" } },
	{ id = 47, main = "sécurité", full = "besoin de sécurité ", synonyms = { "assurance", "fiabilité" } },
	{ id = 48, main = "sens", full = "besoin de sens ", synonyms = { "but", "direction" } },
	{ id = 49, main = "sérénité", full = "besoin de sérénité ", synonyms = { "calme", "solitude" } },
	{ id = 50, main = "soins", full = "besoin de soins ", synonyms = { "assistance", "secours" } },
	{ id = 51, main = "partir", full = "besoin de partir ", synonyms = { "abandonner", "quitter" } },
	{ id = 52, main = "souplesse", full = "besoin de souplesse ", synonyms = { "adaptation", "flexibilité" } },
	{ id = 53, main = "aide", full = "besoin d'aide ", synonyms = { "collaboration", "coopération" } },
	{ id = 54, main = "spiritualité", full = "besoin de spiritualité ", synonyms = { "élévation", "recueillement" } },
	{ id = 55, main = "stabilité", full = "besoin de stabilité ", synonyms = { "équilibre", "solidité" } },
	{ id = 56, main = "victoire", full = "besoin de victoire ", synonyms = { "accomplir", "réussir" } },
	{ id = 57, main = "écoute", full = "besoin d'écoute ", synonyms = { "attention", "compréhension" } },
	{ id = 58, main = "honnêteté", full = "besoin d'honnêteté ", synonyms = { "droiture", "intégrité" } },
	{ id = 59, main = "nourriture", full = "besoin de nourriture ", synonyms = { "réserves", "ressources" } },
}

return M
